// Workspace Mock数据 - 用于所有工作区页面

// ============ 统计数据 ============

export const workspaceStats = [
  {
    title: '活跃对话',
    value: '47',
    change: { value: '+12%', trend: 'up' as const },
    description: '相比上周',
  },
  {
    title: '待处理请求',
    value: '23',
    change: { value: '-8%', trend: 'down' as const },
    description: '相比上周',
  },
  {
    title: '今日已解决',
    value: '156',
    change: { value: '+24%', trend: 'up' as const },
    description: '相比昨天',
  },
  {
    title: '平均响应时间',
    value: '2.4分钟',
    change: { value: '-15%', trend: 'down' as const },
    description: '相比上周',
  },
]

export const channelStats = [
  {
    title: '活跃渠道',
    value: '4',
    description: '运行中',
  },
  {
    title: '今日消息数',
    value: '335',
    change: { value: '+18%', trend: 'up' as const },
    description: '相比昨天',
  },
  {
    title: '平均响应时间',
    value: '1.8分钟',
    change: { value: '-12%', trend: 'down' as const },
    description: '相比上周',
  },
  {
    title: '覆盖率',
    value: '24/7',
    description: '全天候',
  },
]

// ============ 对话数据 ============

export const conversations = [
  {
    id: 1,
    user: {
      name: '张伟',
      avatar: null,
      initials: 'ZW',
    },
    subject: '关于运费问题的咨询',
    preview: '我注意到运费相当高...',
    status: 'needs_review' as const,
    statusLabel: '待审核',
    queue: 'needs_review' as const,
    timestamp: '2小时前',
    dateTime: '2024-01-20T10:00:00',
  },
  {
    id: 2,
    user: {
      name: '李娜',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
      initials: 'LN',
    },
    subject: '产品退货申请',
    preview: '我想退回最近的订单...',
    status: 'awaiting_approval' as const,
    statusLabel: '等待批准',
    queue: 'awaiting_approval' as const,
    timestamp: '4小时前',
    dateTime: '2024-01-20T08:00:00',
  },
  {
    id: 3,
    user: {
      name: '王芳',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
      initials: 'WF',
    },
    subject: '保修问题咨询',
    preview: '这款产品有保修吗？',
    status: 'follow_up' as const,
    statusLabel: '需要跟进',
    queue: 'follow_up' as const,
    timestamp: '1天前',
    dateTime: '2024-01-19T12:00:00',
  },
  {
    id: 4,
    user: {
      name: '刘强',
      avatar: null,
      initials: 'LQ',
    },
    subject: '支付问题',
    preview: '我的支付被拒绝了但我被扣款了...',
    status: 'needs_review' as const,
    statusLabel: '待审核',
    queue: 'needs_review' as const,
    timestamp: '3小时前',
    dateTime: '2024-01-20T09:00:00',
  },
  {
    id: 5,
    user: {
      name: '陈静',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
      initials: 'CJ',
    },
    subject: '批量订单询价',
    preview: '有兴趣下批量订单...',
    status: 'awaiting_approval' as const,
    statusLabel: '等待批准',
    queue: 'awaiting_approval' as const,
    timestamp: '5小时前',
    dateTime: '2024-01-20T07:00:00',
  },
  {
    id: 6,
    user: {
      name: '赵敏',
      avatar: null,
      initials: 'ZM',
    },
    subject: '配送延迟',
    preview: '我的订单本应该昨天到达...',
    status: 'follow_up' as const,
    statusLabel: '需要跟进',
    queue: 'follow_up' as const,
    timestamp: '2天前',
    dateTime: '2024-01-18T14:00:00',
  },
  {
    id: 7,
    user: {
      name: '孙磊',
      avatar: null,
      initials: 'SL',
    },
    subject: '发票开具请求',
    preview: '我需要开具增值税专用发票...',
    status: 'needs_review' as const,
    statusLabel: '待审核',
    queue: 'needs_review' as const,
    timestamp: '6小时前',
    dateTime: '2024-01-20T06:00:00',
  },
  {
    id: 8,
    user: {
      name: '周杰',
      avatar: 'https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
      initials: 'ZJ',
    },
    subject: '账户安全问题',
    preview: '我的账户登录异常...',
    status: 'awaiting_approval' as const,
    statusLabel: '等待批准',
    queue: 'awaiting_approval' as const,
    timestamp: '7小时前',
    dateTime: '2024-01-20T05:00:00',
  },
]

export const messageThreads = {
  1: [
    {
      id: 1,
      sender: 'customer',
      content: '我注意到我最近订单的运费非常高。有什么方法可以降低这个费用吗？',
      timestamp: '2小时前',
    },
    {
      id: 2,
      sender: 'agent',
      content: '感谢您的咨询。让我为您查看一下您所在地区可用的配送选项。请稍候。',
      timestamp: '1小时45分前',
    },
    {
      id: 3,
      sender: 'agent',
      content: '我已经为您找到了更经济的配送方式，可以节省约30元运费。我现在就为您调整订单。',
      timestamp: '1小时30分前',
    },
  ],
  2: [
    {
      id: 1,
      sender: 'customer',
      content: '您好，我想退回订单号为 #ORD-12345 的商品，因为尺寸不合适。',
      timestamp: '4小时前',
    },
    {
      id: 2,
      sender: 'agent',
      content: '好的，我来帮您处理退货。根据我们的退货政策，商品在收到后7天内可以无理由退货。请问您收到货物多久了？',
      timestamp: '3小时45分前',
    },
  ],
}

// ============ 知识库数据 ============

export const articles = [
  {
    id: 1,
    title: '新手入门指南',
    status: 'live' as const,
    statusLabel: '已发布',
    author: {
      name: '李明',
      avatar: null,
      initials: 'LM',
    },
    updated: '2小时前',
    dateTime: '2024-01-20T10:00:00',
    views: 1234,
    category: '文档',
  },
  {
    id: 2,
    title: '定价和套餐说明',
    status: 'live' as const,
    statusLabel: '已发布',
    author: {
      name: '王华',
      avatar: null,
      initials: 'WH',
    },
    updated: '1天前',
    dateTime: '2024-01-19T12:00:00',
    views: 2156,
    category: '计费',
  },
  {
    id: 3,
    title: '退货政策',
    status: 'review' as const,
    statusLabel: '审核中',
    author: {
      name: '刘洋',
      avatar: null,
      initials: 'LY',
    },
    updated: '3天前',
    dateTime: '2024-01-17T09:00:00',
    views: 845,
    category: '政策',
  },
  {
    id: 4,
    title: '配送信息',
    status: 'draft' as const,
    statusLabel: '草稿',
    author: {
      name: '张丽',
      avatar: null,
      initials: 'ZL',
    },
    updated: '5天前',
    dateTime: '2024-01-15T14:00:00',
    views: 0,
    category: '配送',
  },
  {
    id: 5,
    title: '账户安全设置',
    status: 'live' as const,
    statusLabel: '已发布',
    author: {
      name: '陈强',
      avatar: null,
      initials: 'CQ',
    },
    updated: '1周前',
    dateTime: '2024-01-13T11:00:00',
    views: 3421,
    category: '安全',
  },
  {
    id: 6,
    title: 'API接入文档',
    status: 'live' as const,
    statusLabel: '已发布',
    author: {
      name: '赵雪',
      avatar: null,
      initials: 'ZX',
    },
    updated: '3天前',
    dateTime: '2024-01-17T15:00:00',
    views: 987,
    category: '技术文档',
  },
  {
    id: 7,
    title: '常见问题解答',
    status: 'review' as const,
    statusLabel: '审核中',
    author: {
      name: '孙涛',
      avatar: null,
      initials: 'ST',
    },
    updated: '1天前',
    dateTime: '2024-01-19T09:00:00',
    views: 456,
    category: 'FAQ',
  },
  {
    id: 8,
    title: '发票开具指南',
    status: 'live' as const,
    statusLabel: '已发布',
    author: {
      name: '周敏',
      avatar: null,
      initials: 'ZM',
    },
    updated: '4天前',
    dateTime: '2024-01-16T13:00:00',
    views: 1543,
    category: '财务',
  },
]

export const sources = [
  {
    id: 1,
    name: '产品文档',
    type: '网页抓取' as const,
    url: 'https://example.com/docs',
    lastSync: '1小时前',
    articles: 45,
  },
  {
    id: 2,
    name: 'FAQ数据库',
    type: 'CSV导入' as const,
    url: null,
    lastSync: '1天前',
    articles: 23,
  },
  {
    id: 3,
    name: '客服工单',
    type: '集成' as const,
    url: null,
    lastSync: '30分钟前',
    articles: 156,
  },
]

export const reviewQueue = [
  {
    id: 1,
    title: '更新退款政策',
    author: {
      name: '王磊',
      initials: 'WL',
    },
    type: '更新' as const,
    submittedAt: '2小时前',
  },
  {
    id: 2,
    title: '新产品分类FAQ',
    author: {
      name: '李芳',
      initials: 'LF',
    },
    type: '新增' as const,
    submittedAt: '5小时前',
  },
  {
    id: 3,
    title: '配送区域扩展说明',
    author: {
      name: '张伟',
      initials: 'ZW',
    },
    type: '更新' as const,
    submittedAt: '1天前',
  },
]

// ============ AI训练建议数据 ============

export const trainingSuggestions = [
  {
    id: 1,
    suggestion: '添加价格层级对比表',
    source: '聊天',
    status: 'new' as const,
    statusLabel: '新建议',
    priority: 'high' as const,
    priorityLabel: '高',
    frequency: 12,
    lastSeen: '1小时前',
  },
  {
    id: 2,
    suggestion: '更新退货时效说明',
    source: '邮件',
    status: 'needs_approval' as const,
    statusLabel: '待批准',
    priority: 'medium' as const,
    priorityLabel: '中',
    frequency: 8,
    lastSeen: '3小时前',
  },
  {
    id: 3,
    suggestion: '明确国际配送说明',
    source: '聊天',
    status: 'backlog' as const,
    statusLabel: '待办事项',
    priority: 'low' as const,
    priorityLabel: '低',
    frequency: 5,
    lastSeen: '1天前',
  },
  {
    id: 4,
    suggestion: '添加批量订单折扣信息',
    source: '邮件',
    status: 'new' as const,
    statusLabel: '新建议',
    priority: 'high' as const,
    priorityLabel: '高',
    frequency: 15,
    lastSeen: '2小时前',
  },
  {
    id: 5,
    suggestion: '创建保修注册指南',
    source: '聊天',
    status: 'new' as const,
    statusLabel: '新建议',
    priority: 'medium' as const,
    priorityLabel: '中',
    frequency: 7,
    lastSeen: '4小时前',
  },
  {
    id: 6,
    suggestion: '更新支付方式列表',
    source: '社交媒体',
    status: 'needs_approval' as const,
    statusLabel: '待批准',
    priority: 'low' as const,
    priorityLabel: '低',
    frequency: 3,
    lastSeen: '2天前',
  },
  {
    id: 7,
    suggestion: '添加礼品包装选项说明',
    source: '聊天',
    status: 'backlog' as const,
    statusLabel: '待办事项',
    priority: 'low' as const,
    priorityLabel: '低',
    frequency: 4,
    lastSeen: '3天前',
  },
  {
    id: 8,
    suggestion: '优化发票开具流程说明',
    source: '邮件',
    status: 'new' as const,
    statusLabel: '新建议',
    priority: 'high' as const,
    priorityLabel: '高',
    frequency: 10,
    lastSeen: '5小时前',
  },
  {
    id: 9,
    suggestion: '增加会员权益说明',
    source: '聊天',
    status: 'needs_approval' as const,
    statusLabel: '待批准',
    priority: 'medium' as const,
    priorityLabel: '中',
    frequency: 6,
    lastSeen: '1天前',
  },
  {
    id: 10,
    suggestion: '补充售后服务政策',
    source: '社交媒体',
    status: 'backlog' as const,
    statusLabel: '待办事项',
    priority: 'medium' as const,
    priorityLabel: '中',
    frequency: 9,
    lastSeen: '6小时前',
  },
]

// ============ 团队数据 ============

export const teamMembers = [
  {
    id: 1,
    name: '李明',
    email: 'liming@petal.com',
    role: 'owner' as const,
    roleLabel: '所有者',
    status: 'active' as const,
    statusLabel: '活跃',
    avatar: null,
    initials: 'LM',
    joined: '2024年1月',
    lastActive: '5分钟前',
  },
  {
    id: 2,
    name: '王华',
    email: 'wanghua@petal.com',
    role: 'admin' as const,
    roleLabel: '管理员',
    status: 'active' as const,
    statusLabel: '活跃',
    avatar: null,
    initials: 'WH',
    joined: '2024年1月',
    lastActive: '1小时前',
  },
  {
    id: 3,
    name: '刘洋',
    email: 'liuyang@petal.com',
    role: 'reviewer' as const,
    roleLabel: '审核员',
    status: 'active' as const,
    statusLabel: '活跃',
    avatar: null,
    initials: 'LY',
    joined: '2024年2月',
    lastActive: '2小时前',
  },
  {
    id: 4,
    name: '张丽',
    email: 'zhangli@petal.com',
    role: 'reviewer' as const,
    roleLabel: '审核员',
    status: 'active' as const,
    statusLabel: '活跃',
    avatar: null,
    initials: 'ZL',
    joined: '2024年2月',
    lastActive: '3小时前',
  },
  {
    id: 5,
    name: '陈强',
    email: 'chenqiang@petal.com',
    role: 'agent' as const,
    roleLabel: '客服',
    status: 'invited' as const,
    statusLabel: '已邀请',
    avatar: null,
    initials: 'CQ',
    joined: '已邀请',
    lastActive: '从未',
  },
  {
    id: 6,
    name: '赵雪',
    email: 'zhaoxue@petal.com',
    role: 'agent' as const,
    roleLabel: '客服',
    status: 'active' as const,
    statusLabel: '活跃',
    avatar: null,
    initials: 'ZX',
    joined: '2024年3月',
    lastActive: '10分钟前',
  },
]

// ============ 渠道数据 ============

export const channels = [
  {
    id: 1,
    name: '网页聊天',
    type: 'web' as const,
    typeLabel: '网页',
    status: 'live' as const,
    statusLabel: '运行中',
    messagesToday: 234,
    avgResponseTime: '1.2分钟',
    deployUrl: 'chat.petal.com',
    description: '网站实时聊天小工具',
  },
  {
    id: 2,
    name: '邮件',
    type: 'email' as const,
    typeLabel: '邮件',
    status: 'live' as const,
    statusLabel: '运行中',
    messagesToday: 89,
    avgResponseTime: '2.5分钟',
    deployUrl: null,
    description: 'support@petal.com',
  },
  {
    id: 3,
    name: '社交媒体',
    type: 'social' as const,
    typeLabel: '社交媒体',
    status: 'queued' as const,
    statusLabel: '排队中',
    messagesToday: 12,
    avgResponseTime: '5.2分钟',
    deployUrl: null,
    description: 'Facebook、Twitter集成',
  },
  {
    id: 4,
    name: '语音',
    type: 'voice' as const,
    typeLabel: '语音',
    status: 'planned' as const,
    statusLabel: '计划中',
    messagesToday: 0,
    avgResponseTime: null,
    deployUrl: null,
    description: '电话支持（即将推出）',
  },
]

// ============ 设置数据 ============

export const workspaceSettings = {
  basics: {
    workspaceName: 'Petal 客服',
    displayUrl: 'petal.com',
    description: 'Petal 客户支持工作空间',
  },
  branding: {
    primaryColor: '#6366f1',
    logo: null,
  },
  notifications: {
    email: true,
    slack: false,
    webhook: '',
  },
  security: {
    twoFactor: true,
    sessionTimeout: 30,
    ipWhitelist: [],
  },
  api: {
    keys: [
      {
        id: 1,
        name: '生产环境 API 密钥',
        key: 'pk_live_••••••••••••1234',
        created: '2024-01-15',
        lastUsed: '2024-01-20',
      },
      {
        id: 2,
        name: '开发环境 API 密钥',
        key: 'pk_test_••••••••••••5678',
        created: '2024-01-10',
        lastUsed: '2024-01-19',
      },
    ],
  },
}
